---
- name: Choose platform based vars
  include_vars: '{{ family }}'
  with_first_found:
    - vars/{{ ansible_os_family }}.yml
    - not-supported.yml
  loop_control:
          loop_var: family

- name: Choose platform prepared task
  include_tasks: '{{ family }}'
  with_first_found:
    - system/{{ ansible_os_family }}.yml
    - system/not-supported.yml
  loop_control:
          loop_var: family

- name: Choose platform based task
  include_tasks: '{{ platform }}'
  with_first_found:
    - System-{{ ansible_system }}.yml
    - not-supported.yml
  loop_control:
          loop_var: platform
