---
- name: Restart windows Jenkins
  win_service:
    name: jenkins
    state: restarted
  notify: Wait for windows Jenkins

- name: Start windows Jenkins
  win_service:
    name: jenkins
    state: started
    enabled: True
  notify: Wait for windows Jenkins

- name: Wait for windows Jenkins
  uri:
    win_url: "http://{{ jenkins2_inventory_ip }}\
        :{{ jenkins2_config_http_port }}\
        {{ jenkins2_context_path | default('') }}/login"
    return_content: True
    status_code: 200
  register: login_page_win
  until: login_page_win.status_code == 200
  retries: 30
  delay: 5
