---
- name: Set Security
  jenkins_script:
    url: 'http://{{ jenkins_inventory_ip }}:{{ jenkins2_config_http_port }}'
    script: "{{ lookup('template', 'configure-security.groovy.j2') }}"
    user: '{{ jenkins2_cli_username }}'
    password: '{{ jenkins2_cli_password }}'
    validate_certs: False
    timeout: 120
  delegate_to: localhost
  notify:
    - Restart windows Jenkins

- name: Force all notified handlers to run
  meta: flush_handlers
