---
#- name: Proxy Configuration
#  jenkins_script:
#    url: 'http://{{ jenkins2_inventory_ip }}:{{ jenkins2_config_http_port }}'
#    script: "{{ lookup('template', 'proxy_configuration.groovy.j2') }}"
#    user: '{{ jenkins2_cli_username }}'
#    password: '{{ jenkins2_cli_password }}'
#    timeout: 120
#  delegate_to: localhost
- name: debuging1
  debug:
    var: '{{ jenkins2_inventory_ip }}'

- name: Update Center Refresh
  jenkins_script:
    url: "http://'{{ jenkins2_inventory_ip }}':{{ jenkins2_config_http_port }}"
    script: "{{ lookup('template', 'update_center_refresh.groovy.j2') }}"
    user: '{{ jenkins2_cli_username }}'
    password: '{{ jenkins2_cli_password }}'
    validate_certs: False
    timeout: 120
  delegate_to: localhost

- name: Install Jenkins plugins
  jenkins_plugin:
    url: 'http://{{ jenkins2_inventory_ip }}:{{ jenkins2_config_http_port }}'
    url_username: '{{ jenkins2_cli_username }}'
    url_password: '{{ jenkins2_cli_password }}'
    name: "{{ item }}"
    owner: "{{ jenkins2_user }}"
    validate_certs: False
    jenkins_home: '{{ jenkins2_home_directory }}'
    state: present
    timeout: "{{ jenkins2_plugins_timeout }}"
  delegate_to: localhost
  register: my_jenkins_plugins
  retries: 10
  delay: 3
  with_items:
    - '{{ (jenkins2_plugins_suggested | union(jenkins2_plugins_list)) | unique }}'
  notify:
    - Restart windows Jenkins

- name: Force all notified handlers to run
  meta: flush_handlers
