---
- name: Create Self-Signed certificate
  win_shell: New-SelfSignedCertificate  -DnsName "{{ ansible_hostname }}" -CertStoreLocation cert:\LocalMachine\My
    #    Export-Certificate -Cert $NewCert -FilePath {{ jenkins2_home_directory }}
    #  become_method: runas
