---
- name: Add unlock script directory
  win_file:
    path: '{{ jenkins2_home_directory }}\init.groovy.d'
    state: directory

- name: Add script for unlock disabling
  win_template:
    src: "disable_unlock.groovy.j2"
    dest: '{{ jenkins2_home_directory }}\init.groovy.d\basic-security.groovy'

- name: Create directory for user
  win_file:
    path: '{{ jenkins2_home_directory }}\users\{{ jenkins2_cli_username }}'
    state: directory

- name: Delete user directory
  win_file:
    path: '{{ jenkins2_home_directory }}\users\{{ jenkins2_cli_username }}'
    state: absent

- name: Force all notified handlers to run
  meta: flush_handlers

- name: Wait for Jenkins starts
  win_wait_for:
    path: '{{ jenkins2_home_directory }}\config.xml'

#- name: Force all notified handlers to run
#  meta: flush_handlers

- name: Remove unlock script
  win_file:
    path: '{{ jenkins2_home_directory }}\init.groovy.d\basic-security.groovy'
    state: absent
  notify:
    - Restart windows Jenkins

- name: Restart windows Jenkins
  win_service:
    name: jenkins
    state: restarted
  notify: Wait for windows Jenkins

- name: Wait for windows Jenkins
  uri:
    url: "http://{{ jenkins2_inventory_ip }}\
        :{{ jenkins2_config_http_port }}\
        {{ jenkins2_context_path | default('') }}/login"
    return_content: True
    status_code: 200
  register: login_page_win
  until: login_page_win.status_code == 200
  retries: 30
  delay: 5

- name: Add script for password set
  win_template:
    src: "reset_user_password.groovy.j2"
    dest: '{{ jenkins2_home_directory }}\init.groovy.d\basic-security.groovy'
  notify:
    - Restart windows Jenkins

- name: Force all notified handlers to run
  meta: flush_handlers

- name: Remove unlock script2
  win_file:
    path: '{{ jenkins2_home_directory }}\init.groovy.d\basic-security.groovy'
    state: absent
  notify:
    - Restart windows Jenkins

- name: Force all notified handlers to run
  meta: flush_handlers
